spring:
  jackson:
    time-zone: Asia/Seoul
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: smartLedger

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 아래 두 줄을 추가하여 스프링 시큐리티의 동작 로그를 활성화합니다.
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springdoc: DEBUG
    com.knusdp.SmartLedger: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized