name: CD Pipeline

on:
  push:
    branches: [ "main", "develop"  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permission For Gradlew & Build gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker Image Tag
        id: set_tag
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "tag=main" >> $GITHUB_OUTPUT
          else
            echo "tag=develop" >> $GITHUB_OUTPUT
          fi

      - name: Docker image build & push
        run: |
          docker build -t ${{secrets.DOCKERHUB_ID}}/sdp:${{ steps.set_tag.outputs.tag }} .
          docker push ${{secrets.DOCKERHUB_ID}}/sdp:${{ steps.set_tag.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_EC2_HOST}}
          username: ${{secrets.AWS_EC2_USERNAME}}
          key: ${{secrets.AWS_EC2_PRIVATEKEY}}
          script: |
            cd ~/sdp
            if [ "${{ github.ref_name }}" == "main" ]; then
              sudo docker compose pull spring-app
              sudo docker compose up -d spring-app
            else
              sudo docker compose pull spring-dev
              sudo docker compose up -d spring-dev
            fi
            
            sudo docker image prune -f  #오래된 도커 이미지 제거